### ISSUE TITLE
Visual tweaks - Without avatar icon is not displayed correctly on authenticated user.

### ISSUE THREAD

**Issue by LucianaQueirolo** [mozilla/fxa-discoverability-shield-study#45]
[Affected versions]:
Firefox Nightly 66.0a1 and above

[Affected Platforms]:
Windows 10

[Prerequisites]:
Add-on installed
Treatment branch set.
Verified account, no avatar set.

[Steps to reproduce]:
1. Click on Avatar icon.
2. Check on doorhanger default avatar image.

[Expected result]:
Without avatar icon is displayed correctly on authenticated user.

[Actual result]:
Without avatar icon is not displayed correctly on authenticated user, the image is duplicated.

[Notes]:
Please find screenshot attached.
![captura de pantalla 9](https://user-images.githubusercontent.com/44404741/51743908-e74b0e00-207c-11e9-89b2-f718c98ba7fc.png)
![verified no avatar expanded](https://user-images.githubusercontent.com/44404741/51743936-ffbb2880-207c-11e9-8ead-29fe1bb1c58f.PNG)

**Comment by SoftVision-CosminMuntean** [comment]
I have managed to reproduce a similar behavior. I think that this issue is related to the email's number of the characters.
The issue is also reproducible if you have an avatar set.

- I have created an email that contains 37 characters. Here is a screenshot of the doorhanger:
![37](https://user-images.githubusercontent.com/19226534/51755377-2f8f1e00-20c7-11e9-8d5e-7cae02c2b1e8.png)

- I have created an email that contains 41 characters. Here is a screenshot of the doorhanger: 
![41](https://user-images.githubusercontent.com/19226534/51755380-328a0e80-20c7-11e9-889b-2416edbd1240.png)
